package de.modellar.wsp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import de.modellar.wsp.model.Person;
import de.modellar.wsp.model.SearchQuery;
import de.modellar.wsp.model.SimpleResponse;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-03-03T11:54:55.812+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://localhost:8080/wsp/PWS/", name = "PWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PWS {

    @WebResult(name = "setPersonResponse", targetNamespace = "http://localhost:8080/wsp/PWS/", partName = "setPersonResponse")
    @WebMethod(action = "http://localhost:8080/wsp/PWS/setPersonData")
    public SimpleResponse setPersonData(
        @WebParam(partName = "setPersonRequest", name = "setPersonRequest", targetNamespace = "http://localhost:8080/wsp/PWS/")
        Person setPersonRequest
    );

    @WebResult(name = "getPersonResponse", targetNamespace = "http://localhost:8080/wsp/PWS/", partName = "getPersonResponse")
    @WebMethod(action = "http://localhost:8080/wsp/PWS/getPersonData")
    public Person getPersonData(
        @WebParam(partName = "getPersonRequest", name = "getPersonRequest", targetNamespace = "http://localhost:8080/wsp/PWS/")
        SearchQuery getPersonRequest
    );
}
