package de.modellar.wsp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-03-03T11:54:55.840+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "PWS", 
                  wsdlLocation = "/META-INF/PWS.wsdl",
                  targetNamespace = "http://localhost:8080/wsp/PWS/") 
public class PWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/wsp/PWS/", "PWS");
    public final static QName PWS = new QName("http://localhost:8080/wsp/PWS/", "PWS");
    static {
        URL url = null;
        try {
            url = new URL("/META-INF/PWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/META-INF/PWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PWS
     */
    @WebEndpoint(name = "PWS")
    public PWS getPWS() {
        return super.getPort(PWS, PWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PWS
     */
    @WebEndpoint(name = "PWS")
    public PWS getPWS(WebServiceFeature... features) {
        return super.getPort(PWS, PWS.class, features);
    }

}
