package de.modellar.tray.model;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-03-20T13:42:35.773+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "Tray", 
                  wsdlLocation = "/META-INF/WSDL_Tray.wsdl",
                  targetNamespace = "http://localhost:8080/Tray/") 
public class WSDLTray_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/Tray/", "Tray");
    public final static QName WSDLTraySOAP = new QName("http://localhost:8080/Tray/", "Tray");
    static {
        URL url = null;
        try {
            url = new URL("/META-INF/WSDL_Tray.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSDLTray_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/META-INF/WSDL_Tray.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSDLTray_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSDLTray_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDLTray_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSDLTray_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSDLTray_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSDLTray_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSDLTray
     */
    @WebEndpoint(name = "Tray")
    public WSDLTray getWSDLTraySOAP() {
        return super.getPort(WSDLTraySOAP, WSDLTray.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  
     *     	Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDLTray
     */
    @WebEndpoint(name = "Tray")
    public WSDLTray getWSDLTraySOAP(WebServiceFeature... features) {
        return super.getPort(WSDLTraySOAP, WSDLTray.class, features);
    }

}
